# Use the official Node.js base image
FROM node:18

# Set the working directory
WORKDIR /Users/loganjmoore/code/battleship

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the application source code to the working directory
COPY . .

# Expose the port your application will run on
EXPOSE 3050

# Start the application
CMD [ "node", "index.js" ]